---
  some_fact: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31646232336333313333613334666164616465306361333938613739656630663463643331303739
          3261333830323263373433666431363636383561613539300a333335313730333766346333653665
          66366233616436326337313233663765373832323265343532366536393430623762666533323062
          6162353965656230620a353062363233343437336432633936633931346536636266353339626335
          3732